#端口号
server:
  port: 8080
#spring配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    name: mystudydb
    url: jdbc:mysql://localhost:3306/webdemo
    username: root
    password: haosql

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5

mybatis:
  #实体类包
  type-aliases-package: com.hutaotao.webdemo.domain
  #配置mapping路径
  mapper-locations: classpath:mybatis-mapping/*.xml
